dist: xenial
language: cpp
env: VERBOSE=1

addons:
  apt:
    packages:
    # Core
      - build-essential
      - libvulkan-dev
    # Modules
      - libasound2-dev
      - libxi-dev

install:
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install vulkan-sdk; fi

git:
  depth: 1
  quiet: true

script:
  - ./run.sh stats
  - ./run.sh build ${CONFIGURATION}

jobs:
  include:
    # Linux GCC
    - os: linux
      compiler: gcc
      env: CONFIGURATION=dbg
    - os: linux
      compiler: gcc
      env: CONFIGURATION=dev
    - os: linux
      compiler: gcc
      env: CONFIGURATION=rls

    # Linux Clang
    - os: linux
      compiler: clang
      env: CONFIGURATION=dbg
    - os: linux
      compiler: clang
      env: CONFIGURATION=dev
    - os: linux
      compiler: clang
      env: CONFIGURATION=rls

    # Windows MSVC
    - os: windows
      env: CONFIGURATION=dbg
    - os: windows
      env: CONFIGURATION=dev
    - os: windows
      env: CONFIGURATION=rls

  # Windows build doesn't work yet
  allow_failures:
    - os: windows
